#!/bin/bash

# Number of docker containers running
count=$(docker ps -q | wc -l | sed -r 's/^0$//g')
# Recent docker container IP
recent_ip=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" $(docker ps -ql))

memory_usage=$(docker stats --no-stream --format 'table {{.MemUsage}}' | sed 's/\.\([0-9]*\)GiB/\1MiB/g' | sed 's/[A-Za-z]*//g' | awk '{sum += $1} END {print sum "MB"}')

echo "$LABEL$count running ($memory_usage)"
